spring.application.name=student-course-graph

#spring.neo4j.uri=${COGNODB_URI:bolt://localhost:7687}
#spring.neo4j.authentication.username=${COGNODB_USERNAME:neo4j}
#spring.neo4j.authentication.password=${COGNODB_PASSWORD:neo4j@9090}


  
# Spring Boot Neo4j Driver Auto-Configuration
#spring.neo4j.uri=${COGNDB_URI:bolt+s://db-e6fbd487.databases.cognodb.com}
#spring.neo4j.authentication.username=${COGNDB_USERNAME:cognodb}
#spring.neo4j.authentication.password=${COGNDB_PASSWORD:77c507b99e0423971b88b8dfdb0638d4}

#bolt+s://db-e6fbd487.databases.cognodb.com 

# CognoDB / Neo4j Bolt Connection Details


# CognoDB / Neo4j Bolt Connection Details

cogndb.uri=${COGNDB_URI}
cogndb.username=${COGNDB_USERNAME}
cogndb.password=${COGNDB_PASSWORD}

server.port=${PORT:8080}


